export const countryCodes = [
  { code: "+91", country: "IN", name: "India" },
  { code: "+1", country: "US", name: "United States" },
  { code: "+44", country: "GB", name: "United Kingdom" },
  { code: "+86", country: "CN", name: "China" },
  { code: "+81", country: "JP", name: "Japan" },
  { code: "+49", country: "DE", name: "Germany" },
  { code: "+33", country: "FR", name: "France" },
  { code: "+39", country: "IT", name: "Italy" },
  { code: "+7", country: "RU", name: "Russia" },
  { code: "+55", country: "BR", name: "Brazil" },
  { code: "+61", country: "AU", name: "Australia" },
  { code: "+82", country: "KR", name: "South Korea" },
  { code: "+34", country: "ES", name: "Spain" },
  { code: "+52", country: "MX", name: "Mexico" },
  { code: "+62", country: "ID", name: "Indonesia" },
  { code: "+31", country: "NL", name: "Netherlands" },
  { code: "+966", country: "SA", name: "Saudi Arabia" },
  { code: "+41", country: "CH", name: "Switzerland" },
  { code: "+90", country: "TR", name: "Turkey" },
  { code: "+46", country: "SE", name: "Sweden" },
  { code: "+48", country: "PL", name: "Poland" },
  { code: "+32", country: "BE", name: "Belgium" },
  { code: "+43", country: "AT", name: "Austria" },
  { code: "+47", country: "NO", name: "Norway" },
  { code: "+45", country: "DK", name: "Denmark" },
  { code: "+358", country: "FI", name: "Finland" },
  { code: "+353", country: "IE", name: "Ireland" },
  { code: "+351", country: "PT", name: "Portugal" },
  { code: "+30", country: "GR", name: "Greece" },
  { code: "+420", country: "CZ", name: "Czech Republic" },
  { code: "+36", country: "HU", name: "Hungary" },
  { code: "+40", country: "RO", name: "Romania" },
  { code: "+380", country: "UA", name: "Ukraine" },
  { code: "+972", country: "IL", name: "Israel" },
  { code: "+971", country: "AE", name: "UAE" },
  { code: "+974", country: "QA", name: "Qatar" },
  { code: "+965", country: "KW", name: "Kuwait" },
  { code: "+968", country: "OM", name: "Oman" },
  { code: "+973", country: "BH", name: "Bahrain" },
  { code: "+98", country: "IR", name: "Iran" },
  { code: "+92", country: "PK", name: "Pakistan" },
  { code: "+880", country: "BD", name: "Bangladesh" },
  { code: "+94", country: "LK", name: "Sri Lanka" },
  { code: "+977", country: "NP", name: "Nepal" },
  { code: "+95", country: "MM", name: "Myanmar" },
  { code: "+66", country: "TH", name: "Thailand" },
  { code: "+84", country: "VN", name: "Vietnam" },
  { code: "+60", country: "MY", name: "Malaysia" },
  { code: "+65", country: "SG", name: "Singapore" },
  { code: "+63", country: "PH", name: "Philippines" },
  { code: "+855", country: "KH", name: "Cambodia" },
  { code: "+852", country: "HK", name: "Hong Kong" },
  { code: "+886", country: "TW", name: "Taiwan" },
  { code: "+64", country: "NZ", name: "New Zealand" },
  { code: "+27", country: "ZA", name: "South Africa" },
  { code: "+234", country: "NG", name: "Nigeria" },
  { code: "+254", country: "KE", name: "Kenya" },
  { code: "+20", country: "EG", name: "Egypt" },
  { code: "+212", country: "MA", name: "Morocco" },
  { code: "+213", country: "DZ", name: "Algeria" },
  { code: "+216", country: "TN", name: "Tunisia" },
  { code: "+233", country: "GH", name: "Ghana" },
  { code: "+251", country: "ET", name: "Ethiopia" },
  { code: "+255", country: "TZ", name: "Tanzania" },
  { code: "+256", country: "UG", name: "Uganda" },
  { code: "+57", country: "CO", name: "Colombia" },
  { code: "+54", country: "AR", name: "Argentina" },
  { code: "+56", country: "CL", name: "Chile" },
  { code: "+51", country: "PE", name: "Peru" },
  { code: "+58", country: "VE", name: "Venezuela" },
  { code: "+593", country: "EC", name: "Ecuador" },
  { code: "+1", country: "CA", name: "Canada" },
  { code: "+53", country: "CU", name: "Cuba" },
  { code: "+507", country: "PA", name: "Panama" },
  { code: "+506", country: "CR", name: "Costa Rica" },
]
